username: daeshaunkmorrison@gmail.com
password: 2001211Nana
phone_number: 9295368025

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Software Engineer
- Data Engineer
- Front End developer
- Backend
- full stack developer


locations:
- Remote
- Alabama
- Alaska
- Arizona
- Arkansas
- California
- Colorado
- Connecticut
- Delaware
- Florida
- Georgia
- Hawaii
- Idaho
- Illinois
- Indiana
- Iowa
- Kansas
- Kentucky
- Louisiana
- Maine
- Maryland
- Massachusetts
- Michigan
- Minnesota
- Mississippi
- Missouri
- Montana
- Nebraska
- Nevada
- New Hampshire
- New Jersey
- New Mexico
- New York
- North Carolina
- North Dakota
- Ohio
- Oklahoma
- Oregon
- Pennsylvania
- Rhode Island
- South Carolina
- South Dakota
- Tennessee
- Texas
- Utah
- Vermont
- Virginia
- Washington
- West Virginia
- Wisconsin
- Wyoming

salary: 60,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: Users\morri\OneDrive\Documents\Coding\LinkedIn-Easy-Apply-Bot\Kevin_Morrison_Resume(Engineer).pdf
  Cover Letter: Users\morri\OneDrive\Documents\Coding\LinkedIn-Easy-Apply-Bot\Cover Letter 2024.pdf
  #Photo: # PATH TO photo


output_filename:
- Users\morri\OneDrive\Documents\Coding\LinkedIn-Easy-Apply-Bot\out.csv

# blacklist:
# - # Company names you want to ignore

experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  - 5 # Executive
  - 6 # Internship